"""
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import time

from numpy import tri

def main():
    start_time = time.process_time()

    num = 1
    while True:
        triangle_number = find_triangle_numbers(num)
        num += 1
        if triangle_number == 28:
            break
    print(triangle_number)
    
    print(f"The program took {round(time.process_time() - start_time, 2)} seconds to run")


def find_triangle_numbers(num):
    sum = 0
    for i in range(1, num + 1):
        sum += i
    return sum


if __name__ == '__main__':
    main()